name: Build and Test

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    branches-ignore:
      - github-action-* #to allow testing of build logic in branches, don't do PR builds for github-action-* branches and instead use branch builds

  push:
    branches:
      - master
      - main
      - github-action-*

jobs:
  check_build_safety:
    name: Check if Build should be done
    runs-on: ubuntu-latest
    steps:
      - name: Supress builds for PRs from branch github-action-*
        if: github.event.pull_request && contains(github.head_ref, 'github-action')
        run: |
          echo "not building PRs with source branch github-action-*"
          exit 1
  setup:
    name: Setup to do something
    needs: check_build_safety
    runs-on: ubuntu-latest
    steps:
      - name: print test message
        run: |
          echo "This is a build message from dredel"
